version: '3'

x-php-build: &php-build
  context: ./docker
  args:
    PHP_VERSION: 8.1.13
    INSTALL_PHP_XDEBUG: ${DOCKER_INSTALL_PHP_XDEBUG:-false}

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      <<: *php-build
      dockerfile: php-fpm/Dockerfile
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-a-custom.conf:ro
      - ./:/app
    depends_on:
      - mysql
      - redis

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'

  redis:
    image: 'redis:alpine'
    volumes:
      - 'redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  workspace:
    build:
      <<: *php-build
      dockerfile: workspace/Dockerfile
    init: true
    volumes:
      - ./docker/workspace/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./:/app
    depends_on:
      - mysql
      - redis

volumes:
  mysql:
  redis:
